In [1]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt


reading data

In [10]:
df=pd.read_csv('corona_dataset.csv')

In [11]:
df.shape

(29, 6)

In [12]:
df.head()

fever  body_pain  age  runny_nose  difficult_breath  infection_prob
0     38          0   45           0                 0               0
1     43          1   34           0                 1               1
2     44          0   20           1                 0               0
3     37          1   45           1                 1               1
4     98          1   45           0                 2               1

In [13]:
df.tail()

fever  body_pain  age  runny_nose  difficult_breath  infection_prob
24     99          1   35           0                 1               1
25    100          0   24           0                 0               0
26    101          1   42           0                 2               1
27    102          1   47           0                 2               1
28    101          1   36           0                 2               1

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29 entries, 0 to 28
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fever             29 non-null     int64
 1   body_pain         29 non-null     int64
 2   age               29 non-null     int64
 3   runny_nose        29 non-null     int64
 4   difficult_breath  29 non-null     int64
 5   infection_prob    29 non-null     int64
dtypes: int64(6)
memory usage: 1.5 KB


In [15]:
df.isnull().sum()

fever               0
body_pain           0
age                 0
runny_nose          0
difficult_breath    0
infection_prob      0
dtype: int64

In [16]:
df['difficult_breath'].value_counts() #it shows how many diff values diff breath contains

0    12
2    10
1     7
Name: difficult_breath, dtype: int64

In [17]:
df.describe()

fever  body_pain        age  runny_nose  difficult_breath  \
count   29.000000  29.000000  29.000000   29.000000         29.000000   
mean    72.413793   0.517241  33.379310    0.310345          0.931034   
std     27.817668   0.508548  10.026443    0.470824          0.883622   
min     37.000000   0.000000  18.000000    0.000000          0.000000   
25%     43.000000   0.000000  24.000000    0.000000          0.000000   
50%     87.000000   1.000000  35.000000    0.000000          1.000000   
75%     99.000000   1.000000  44.000000    1.000000          2.000000   
max    102.000000   1.000000  47.000000    1.000000          2.000000   

       infection_prob  
count       29.000000  
mean         0.655172  
std          0.483725  
min          0.000000  
25%          0.000000  
50%          1.000000  
75%          1.000000  
max          1.000000

In [18]:
X = df.iloc[:,:5].values  #values is used to convert it into array
Y =df.iloc[:,5].values

In [19]:
X

array([[ 38,   0,  45,   0,   0],
       [ 43,   1,  34,   0,   1],
       [ 44,   0,  20,   1,   0],
       [ 37,   1,  45,   1,   1],
       [ 98,   1,  45,   0,   2],
       [ 76,   1,  32,   1,   0],
       [ 88,   0,  20,   0,   0],
       [100,   1,  35,   0,   2],
       [ 79,   0,  20,   0,   1],
       [ 95,   1,  44,   0,   2],
       [ 44,   0,  35,   1,   0],
       [ 43,   1,  45,   0,   1],
       [ 38,   0,  21,   1,   0],
       [ 38,   0,  24,   1,   0],
       [ 38,   0,  18,   1,   0],
       [ 44,   1,  35,   0,   2],
       [ 38,   0,  20,   0,   0],
       [ 44,   0,  38,   0,   1],
       [ 95,   1,  35,   0,   2],
       [ 90,   0,  36,   0,   1],
       [102,   0,  25,   0,   2],
       [101,   1,  45,   1,   2],
       [ 87,   0,  20,   0,   0],
       [ 97,   1,  47,   1,   0],
       [ 99,   1,  35,   0,   1],
       [100,   0,  24,   0,   0],
       [101,   1,  42,   0,   2],
       [102,   1,  47,   0,   2],
       [101,   1,  36,   0,   2]], dtype=int64)

In [20]:
Y

array([0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1], dtype=int64)

dataset splitting

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.25,random_state=0)

In [23]:
X_train

array([[ 76,   1,  32,   1,   0],
       [ 38,   0,  18,   1,   0],
       [ 79,   0,  20,   0,   1],
       [ 38,   0,  20,   0,   0],
       [ 87,   0,  20,   0,   0],
       [ 44,   0,  38,   0,   1],
       [ 43,   1,  34,   0,   1],
       [ 44,   0,  35,   1,   0],
       [101,   1,  36,   0,   2],
       [ 88,   0,  20,   0,   0],
       [ 98,   1,  45,   0,   2],
       [ 95,   1,  35,   0,   2],
       [ 90,   0,  36,   0,   1],
       [ 95,   1,  44,   0,   2],
       [100,   1,  35,   0,   2],
       [ 99,   1,  35,   0,   1],
       [ 37,   1,  45,   1,   1],
       [ 38,   0,  45,   0,   0],
       [101,   1,  45,   1,   2],
       [ 44,   1,  35,   0,   2],
       [ 38,   0,  21,   1,   0]], dtype=int64)

In [24]:
X_test

array([[ 44,   0,  20,   1,   0],
       [102,   0,  25,   0,   2],
       [ 97,   1,  47,   1,   0],
       [ 38,   0,  24,   1,   0],
       [ 43,   1,  45,   0,   1],
       [100,   0,  24,   0,   0],
       [102,   1,  47,   0,   2],
       [101,   1,  42,   0,   2]], dtype=int64)

In [25]:
Y_train

array([1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0],
      dtype=int64)

In [26]:
Y_test

array([0, 1, 1, 0, 1, 0, 1, 1], dtype=int64)

In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
clf= LogisticRegression()

In [29]:
clf.fit(X_train,Y_train)

LogisticRegression()

In [30]:
#y_pred = clf.predict(X_test)

In [31]:
#y_pred

array([0, 1, 1, 0, 1, 1, 1, 1], dtype=int64)

In [32]:
#from sklearn.metrics import confusion_matrix,recall_score,precision_score,f1_score

In [33]:
#cm = confusion_matrix(Y_test,y_pred)

In [34]:
#cm

array([[2, 1],
       [0, 5]], dtype=int64)

In [35]:
#recall_score(Y_test,y_pred)

1.0

In [36]:
#precision_score(Y_test,y_pred)

0.8333333333333334

In [37]:
#f1_score(Y_test,y_pred)

0.9090909090909091

In [43]:
#df.loc[22]

fever               87
body_pain            0
age                 20
runny_nose           0
difficult_breath     0
infection_prob       0
Name: 22, dtype: int64

In [44]:
inputFeatures = [99.15,1,14,0,0]
infection_prob = clf.predict_proba([inputFeatures])[0][1]

In [45]:
infection_prob

0.4600795428896066